package com.klt.materialyoutest.ui.theme

import androidx.compose.ui.graphics.Color

val Green = Color(0xFF006d32)

val md_theme_light_primary = Color(0xFF006d32)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00184A)
val md_theme_light_secondary = Color(0xFF5A5E6C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDFE2F3)
val md_theme_light_onSecondaryContainer = Color(0xFF171B27)
val md_theme_light_tertiary = Color(0xFF6F576C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF8D9F2)
val md_theme_light_onTertiaryContainer = Color(0xFF271527)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFE)
val md_theme_light_onBackground = Color(0xFF1B1B1E)
val md_theme_light_surface = Color(0xFFFEFBFE)
val md_theme_light_onSurface = Color(0xFF1B1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE3E2E9)
val md_theme_light_onSurfaceVariant = Color(0xFF46464C)
val md_theme_light_outline = Color(0xFF76767D)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inverseOnSurface = Color(0xFFF3F0F3)
val md_theme_light_inversePrimary = Color(0xFFB3C5FF)
val md_theme_light_surfaceTint = Color(0xFF495C93)
val md_theme_light_surfaceTintColor = Color(0xFF495C93)

val md_theme_dark_primary = Color(0xFF006d32)
val md_theme_dark_onPrimary = Color(0xFF192D62)
val md_theme_dark_primaryContainer = Color(0xFF31447A)
val md_theme_dark_onPrimaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_secondary = Color(0xFFC3C6D6)
val md_theme_dark_onSecondary = Color(0xFF2C303D)
val md_theme_dark_secondaryContainer = Color(0xFF434654)
val md_theme_dark_onSecondaryContainer = Color(0xFFDFE2F3)
val md_theme_dark_tertiary = Color(0xFFDBBED6)
val md_theme_dark_onTertiary = Color(0xFF3E2A3C)
val md_theme_dark_tertiaryContainer = Color(0xFF564053)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8D9F2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1B1E)
val md_theme_dark_onBackground = Color(0xFFE4E2E5)
val md_theme_dark_surface = Color(0xFF1B1B1E)
val md_theme_dark_onSurface = Color(0xFFE4E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF46464C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C6CD)
val md_theme_dark_outline = Color(0xFF909097)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E5)
val md_theme_dark_inverseOnSurface = Color(0xFF303033)
val md_theme_dark_inversePrimary = Color(0xFF495C93)
val md_theme_dark_surfaceTint = Color(0xFFB3C5FF)
val md_theme_dark_surfaceTintColor = Color(0xFFB3C5FF)


val seed = Color(0xFF11275B)